spring:
  application:
    name: auto-offer
  datasource:
    url: jdbc:mysql://localhost:3306/vue_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
